name: Setup

description: Ponder monorepo action setup

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile
